### ISSUE TITLE
where to put dll ?

### ISSUE THREAD

**Issue by aimcat** [Finguimbrine/CSGO-Cheat-Loader2#1]
hi , maybe this weird question xd , where i can upload my dll ?
and where to put it at source

**Comment by Finguimbrine** [comment]
Follow these steps : encrypt the dll using the dlltool, drop it on any web server, put an user agent on the web server, then reference all the GetVariable stuff into the server sided auth.gg vars

**Comment by aimcat** [comment]
can i got your discord please for more info about this ?
