### ISSUE TITLE
this is what i got after follow that , maybe im wrong

### ISSUE THREAD

**Issue by aimcat** [Finguimbrine/CSGO-Cheat-Loader2#2]
so i've put my dll in to the server
and create httaccess
"    SetEnvIfNoCase User-Agent "CustomUseragentString" good_bot
    <FilesMatch ".dll">
    	Order Deny,Allow
    	Deny from All
    	Allow from env=good_bot
    </FilesMatch>"

ad create var like this at auth : https://prnt.sc/qigaxs

i got this error when trying inject into d3d9test
https://prnt.sc/qigace

**Comment by Finguimbrine** [comment]
First, auth.gg uses secrets instead of names, so please replace all the var names, second the User-Agent is wrong, it should be good_bot in your case

**Comment by aimcat** [comment]
i guest im 1 step again to make its work , now the error notice after inject to d3d9test its 403 forbidden , and maybe that because a htaccess i create

here a screenshot at vs2019 : https://prnt.sc/qigxw6
and here screenshot at auth : https://prnt.sc/qigy93

also do i need create var for this ? " // decrypt the dll using a pass lol "

**Comment by Finguimbrine** [comment]
The crypt_pass should not be GetVariable("good_bot")

**Comment by aimcat** [comment]
i've make var for crypt_pass at auth gg 
and put crypt_pass at vs2019 with serial 
its still didnt want get my dll 

can i got your discord please ?

**Comment by Finguimbrine** [comment]
My discord is FinGu#1337

**Comment by Finguimbrine** [comment]
fixed and closed +rep aimcat
