### ISSUE TITLE
What value to put for user agent

### ISSUE THREAD

**Issue by PatrickMuEditor** [Finguimbrine/CSGO-Cheat-Loader2#4]
So I figured out where to put all the variables (sorry @Finguimbrine) the only one I'm stuck on is user_agent what do I do for that one. I read the other issue, you said to "put a user agent on the webserver" sorry but how do I do that?
I've put the .dll on my web server, just what do I put in htaccess?
Sorry for being stupid about "where to put the vars"

Also so the crypt_pass is 
byte[] encrypted = AES_Encrypt(unencrypted,Encoding.UTF8.GetBytes("**XSaBw6JkWFZh7PBgLQb5TndqzEkm**"));

Right? If not, where is the pass outputted?

**Comment by Finguimbrine** [comment]
Comment the user agent line

**Comment by PatrickMuEditor** [comment]
![image](https://user-images.githubusercontent.com/44944178/76085143-5f3a7600-5fa9-11ea-8b73-4cc0dd134197.png)

**Comment by Finguimbrine** [comment]
comment user agent's line

**Comment by PatrickMuEditor** [comment]
`mac.Headers.Add("User-Agent", Handler.GetVariable("user_agent")); //add headers using a sv side var(auth.gg)`

**Comment by Finguimbrine** [comment]
Add an // in the front of the User-Agent line...

**Comment by PatrickMuEditor** [comment]
I really trying to understand but why would I do a comment on the user-agent line? 
Are you sure? Like this??
`//mac.Headers.Add("User-Agent", Handler.GetVariable("user_agent")); //add headers using a sv side var(auth.gg)`

**Comment by Finguimbrine** [comment]
Bcs youre not using an .htaccess, and without a proper setup one, you can have problems

**Comment by PatrickMuEditor** [comment]
Ah ok so I don't need to use this line?

**Comment by PatrickMuEditor** [comment]
Also where do I get the actual crypt pass from to put as a variable in auth.gg?

![image](https://user-images.githubusercontent.com/44944178/76114737-b1e25500-5fde-11ea-8e8c-6e911614c5b6.png)

**Comment by Finguimbrine** [comment]
Contact me on discord : FinGu#1337
I dont like using github for this
