### ISSUE TITLE
Cant inject dll

### ISSUE THREAD

**Issue by playday3008** [Finguimbrine/CSGO-Cheat-Loader2#5]
In debug console i have
`[InjectDependency] GetProcAddress failed`
`[ProcessImportTable] failed to obtain module handle`
`[InjectDependency] GetProcAddress failed`
`[ProcessImportTable] failed to obtain module handle`

**Comment by Finguimbrine** [comment]
The dll youre trying to inject probably needs dependencies, and the manual map that IS included in this source cant handle it

**Comment by playday3008** [comment]
No, my dll successfully injected by, Inflame, Xenos, GH Injector without dependencies

**Comment by Finguimbrine** [comment]
The manual map that IS included on this source....

**Comment by playday3008** [comment]
I know this, output in debug console from file `ManualMapInjector.cs` IDK why I can't inject dll by compiled exe from this source

**Comment by Finguimbrine** [comment]
Bcs the manual mapper i used in this source doenst fix/handle exceptions correctly, so it crashes when it finds one while injecting

**Comment by playday3008** [comment]
Open issue, maybe someone can fix this

**Comment by Finguimbrine** [comment]
Just use another library instead of the manual mapper im using

**Comment by playday3008** [comment]
I am idiot, sorry
